apiVersion: v1
kind: Service
metadata:
  name: {{ include "signoz-metrics-adapter.fullname" . }}
  labels:
    {{- include "signoz-metrics-adapter.labels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: 443
      targetPort: 6443
      protocol: TCP
  selector:
    {{- include "signoz-metrics-adapter.selectorLabels" . | nindent 4 }}
