replicas: 1

verbosity: 2

imagePullSecrets:
  - name: github-registry

signoz:
  existingSecret: "signoz-credentials"
  secretKeys:
    url: url
    token: token
  timeRangeMinutes: 5
  metrics: ['phpfpm_active_processes']
  filterExpression: "deployment.environment = 'dev'"

serviceAccount:
  name: ""

resources: {}
